# Generated by Django 5.1 on 2024-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statewise_monthlyproductio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=15)),
                ('Country_code', models.CharField(max_length=5)),
                ('State', models.CharField(max_length=50)),
                ('State_code', models.CharField(max_length=10)),
                ('State_type', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Subcategory', models.CharField(max_length=20)),
                ('Variable', models.CharField(max_length=30)),
                ('Unit', models.CharField(max_length=10)),
                ('Value', models.CharField(max_length=20)),
            ],
        ),
    ]
