# Generated by Django 5.1 on 2024-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0002_statewise_monthlyproductio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=7)),
                ('Sector', models.CharField(max_length=20)),
                ('Unit', models.CharField(max_length=10)),
                ('Energy_Sold', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
