# Generated by Django 5.1 on 2024-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0003_energy_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='power_supp_jantojul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=30)),
                ('Peak_Demand_MW', models.IntegerField(max_length=20)),
                ('Peak_Met_MW', models.IntegerField(max_length=20)),
                ('Difference_MW', models.IntegerField(max_length=20)),
                ('Difference_percent', models.IntegerField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
    ]
