# Generated by Django 5.1 on 2024-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0004_power_supp_jantojul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_supp_jantojul',
            name='Difference_MW',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supp_jantojul',
            name='Difference_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supp_jantojul',
            name='Peak_Demand_MW',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='power_supp_jantojul',
            name='Peak_Met_MW',
            field=models.IntegerField(),
        ),
    ]
