# Generated by Django 5.1 on 2024-08-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_data', '0005_alter_power_supp_jantojul_difference_mw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_supp_jantojul',
            name='Region',
            field=models.CharField(max_length=50),
        ),
    ]
