# Generated by Django 4.2.4 on 2024-09-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("state_data", "0006_alter_power_supp_jantojul_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("population", models.PositiveIntegerField()),
                ("gdp", models.DecimalField(decimal_places=20, max_digits=20)),
                (
                    "peak_demand_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
                (
                    "peak_production_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
                (
                    "solar_production_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
                (
                    "coal_production_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
                (
                    "wind_production_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
                (
                    "nuclear_production_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
                (
                    "total_production_mw",
                    models.DecimalField(decimal_places=20, max_digits=20),
                ),
            ],
        ),
    ]
