# Generated by Django 4.2.4 on 2024-09-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("state_data", "0007_energydata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energydata",
            name="date",
            field=models.CharField(max_length=100),
        ),
    ]
