# Generated by Django 4.2.4 on 2024-09-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("state_data", "0009_alter_energydata_gdp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energydata",
            name="coal_production_mw",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="energydata",
            name="nuclear_production_mw",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="energydata",
            name="peak_demand_mw",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="energydata",
            name="peak_production_mw",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="energydata",
            name="solar_production_mw",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="energydata",
            name="total_production_mw",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="energydata",
            name="wind_production_mw",
            field=models.CharField(max_length=20),
        ),
    ]
